-- ==========================================================
-- เที่ยวมะ (tiaoma) — สร้าง schema ของฐานข้อมูล PostgreSQL
-- ใช้ Flyway เป็นผู้จัดการ (แทน spring.jpa.hibernate.ddl-auto=update)
-- ไฟล์นี้ต้องตรงกับ model ใน src/main/java/com/tiaoma/model/** ทุกตัว
-- ถ้าจะแก้โครงสร้างตาราง อย่าแก้ไฟล์นี้ — ให้เพิ่มไฟล์ V2__..., V3__... ใหม่เท่านั้น
-- =
-- ชนิดคอลัมน์เขียนให้ตรงกับสิ่งที่ Hibernate 6 ใช้ (เพื่อให้ ddl-auto=validate ผ่าน)
--   String ไม่ระบุความยาว -> varchar(255)
--   LocalDateTime        -> timestamp
--   LocalDate            -> date
--   int / Long           -> integer / bigint
-- ==========================================================

-- ---- ผู้ใช้ ---- -------------------------------------------------
create table users (
    id            bigint generated by default as identity primary key,
    name          varchar(100) not null,
    email         varchar(254) not null,
    password_hash varchar(255) not null,
    created_at    timestamp    not null,
    role          varchar(20)  not null,
    constraint uk_users_email unique (email)
);

-- ---- สถานที่ท่องเที่ยว (id เป็น string เช่น "doi-inthanon") -------
create table places (
    id         varchar(100)  primary key,
    name       varchar(255)  not null,
    province   varchar(255)  not null,
    category   varchar(255)  not null,
    short_text varchar(500)  not null,
    hours      varchar(500),
    fee        varchar(500),
    best_time  varchar(500),
    map_query  varchar(255),
    image      varchar(2000),
    accent     integer       not null default 0
);

-- เนื้อหาเต็มของสถานที่ (List<String> description) เรียงตาม sort_order
create table place_descriptions (
    place_id  varchar(100) not null,
    sort_order integer       not null,
    paragraph varchar(4000),
    constraint pk_place_descriptions primary key (place_id, sort_order),
    constraint fk_place_descriptions_place foreign key (place_id)
        references places (id) on delete cascade
);

-- จุดเด่นของสถานที่ (List<String> highlights) เรียงตาม sort_order
create table place_highlights (
    place_id   varchar(100) not null,
    sort_order integer       not null,
    highlight  varchar(500),
    constraint pk_place_highlights primary key (place_id, sort_order),
    constraint fk_place_highlights_place foreign key (place_id)
        references places (id) on delete cascade
);

-- ---- บทความ ------- ----------------------------------------------
create table articles (
    id           bigint generated by default as identity primary key,
    title        varchar(255)  not null,
    summary      varchar(1000) not null,
    image        varchar(255),
    category     varchar(255)  not null,
    published_at date          not null,
    content      varchar(20000)
);

-- ---- รีวิว + ดาว (หนึ่งคน หนึ่งรีวิวต่อหนึ่งสถานที่) ----------------
create table reviews (
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null,
    place_id   varchar(100) not null,
    rating     integer      not null,
    comment    varchar(1000),
    created_at timestamp    not null,
    updated_at timestamp,
    constraint uk_review_user_place unique (user_id, place_id),
    constraint fk_reviews_user foreign key (user_id)
        references users (id) on delete cascade,
    constraint fk_reviews_place foreign key (place_id)
        references places (id) on delete cascade
);

-- ---- ที่เที่ยวโปรด (คีย์ผสม user_id + place_id) -------------------
create table likes (
    user_id    bigint       not null,
    place_id   varchar(100) not null,
    created_at timestamp    not null,
    constraint pk_likes primary key (user_id, place_id),
    constraint fk_likes_user foreign key (user_id)
        references users (id) on delete cascade,
    constraint fk_likes_place foreign key (place_id)
        references places (id) on delete cascade
);

-- ---- โทเคนรีเซ็ตรหัสผ่าน (เก็บเฉพาะ SHA-256 hash) ------------------
create table password_reset_tokens (
    id         bigint      generated by default as identity primary key,
    token_hash varchar(64) not null,
    user_id    bigint      not null,
    expires_at timestamp   not null,
    constraint uk_reset_token_hash unique (token_hash),
    constraint fk_reset_tokens_user foreign key (user_id)
        references users (id) on delete cascade
);

-- ---- ดัชนีสำหรับคิวรี่ที่ใช้บ่อย (ช่วยให้หน้าเว็บเร็วขึ้น) -----------
create index idx_reviews_place    on reviews (place_id);
create index idx_reviews_user     on reviews (user_id);
create index idx_likes_user       on likes (user_id);
create index idx_articles_publish on articles (published_at desc);
